'use client'
import { useEffect, useState } from "react";
import Image from "next/image";
import banerParallax from '@/public/banerParallax.jpg'

export default function Home() {
  const [offsetY, setOffsetY] = useState(0)
  const handleScroll = () => setOffsetY(window.pageYOffset)
  useEffect(()=>{
    window.addEventListener('scroll', handleScroll)
    return ()=>window.removeEventListener('scroll', handleScroll)
  },[])
  return (
    <section>
      <nav className="" style={{transform: `translateY(${offsetY * 0.8}px)`}}>
        <Image src={banerParallax} className="top-0 left-0 h-screen w-full object-cover p-0 m-0" alt="holaaa"/>
      </nav>
      <main className="" style={{transform: `translateY(${offsetY * -0.02}px)`}}>
        <div className="bg-gray-800 ">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, ab fugit facilis consequuntur necessitatibus expedita aut eaque, minima blanditiis porro architecto repellat illum ea quisquam sequi incidunt exercitationem iste vero perspiciatis ducimus ipsam, ex accusamus quos consequatur? Accusantium ducimus, voluptatibus pariatur eius repudiandae ut. Impedit nihil, reprehenderit obcaecati tempore odit sunt. Excepturi, totam, quaerat distinctio commodi recusandae voluptatibus cum voluptatum placeat aperiam ut nulla ducimus tempore, itaque officiis eaque error porro ipsa ipsam. A provident debitis laboriosam accusamus blanditiis ducimus aspernatur ipsam repellat cupiditate. Autem iste quibusdam qui distinctio. Necessitatibus aliquam itaque deleniti illo at inventore molestiae doloribus atque praesentium.
        </div>
      </main>
    </section>
  );
}
